import "./globals.css";
import { Fira_Sans } from "next/font/google";
import NavBar from "./components/navbar";
import Footer from "./components/footer";

import styles from "./layout.module.css";

const fira = Fira_Sans({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${fira.className} ${styles.container}`}>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
